# Copyright (C) 2019-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/gapps/common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps2/common

# Basics
PRODUCT_COPY_FILES += \
    vendor/gapps2/common/proprietary/product/app/CalculatorGooglePrebuilt/CalculatorGooglePrebuilt.apk.prof:$(TARGET_COPY_OUT_PRODUCT)/app/CalculatorGooglePrebuilt/CalculatorGooglePrebuilt.apk.prof \
    vendor/gapps2/common/proprietary/product/app/GoogleContacts/GoogleContacts.apk.prof:$(TARGET_COPY_OUT_PRODUCT)/app/GoogleContacts/GoogleContacts.apk.prof

# Huexxx
PRODUCT_COPY_FILES += \
    vendor/gapps2/common/proprietary/product/etc/sysconfig/google_experience.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google_experience.xml

PRODUCT_PACKAGES += \
    CalculatorGooglePrebuilt \
    CalendarGooglePrebuilt \
    GoogleContacts \
    PrebuiltBugle
